验证以下是我们的特殊情况
$$
\begin{aligned}
E^{\prime \prime}(0)= & -E_{\text {even }}(0) \frac{2 R^2+1}{6}+E_{\text {even }}(\pi) \frac{(-1)^{R-1}}{2} \\
& +\sum_{\mu=1}^{R-1} E_{\text {even }}\left(\frac{\mu \pi}{R}\right) \frac{(-1)^{\mu-1}}{\sin ^2\left(\frac{\mu \pi}{2 R}\right)}
\end{aligned}
$$


In [1]:
import numpy as np
# even 函数前的系数

d=2
# Define random r
r = np.random.randint(1, 10)
r = 5

# Define x_mu
# x_mu = np.array([0] + [(mu * np.pi) / r  for mu in range(1, r)] + [np.pi])
x_mu = np.array([(mu * np.pi) / r  for mu in range(0, r+1)])

Omegas = np.arange(1, r+1)
# q0 = np.array([0] + [-mu**2 for mu in range(1, r + 1)])
q0 = Omegas ** d * (-1 if d % 4 == 2 else 1)
q0 = np.insert(q0, 0, 1 if d == 0 else 0)

# Create matrix A
A = np.array([[1] + [np.cos(n * x) for n in range(1, r + 1)] for x in x_mu])
# A = np.cos(np.outer(x_mu, np.insert(Omegas, 0, 0)))

# Calculate the inverse of A and the dot product with p0
b = np.dot(np.linalg.inv(A).T, q0)

# Calculate the expression for each x_mu
expression_values = np.array(
    [-(2*r**2+1)/6]+
    [(-1)**(mu-1)/ (np.sin(0.5 * (mu * np.pi) / r )**2) for mu in range(1, r)]+
    [(-1)**(r-1)/2])

# Check if the values are equal
are_equal = np.allclose(b , expression_values)
b, expression_values, are_equal

(array([-8.5       , 10.47213595, -2.89442719,  1.52786405, -1.10557281,
         0.5       ]),
 array([-8.5       , 10.47213595, -2.89442719,  1.52786405, -1.10557281,
         0.5       ]),
 True)

In [13]:
np.linalg.norm(expression_values,1)

25.0

In [3]:
0.5 * np.trace(np.linalg.inv(A.T @ A) @ np.outer(q0, q0))

97.05

In [4]:
0.5 * np.linalg.norm(b,2)**2

97.05

In [5]:
A.T @ A

array([[ 6.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         2.22044605e-16,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  3.50000000e+00,  2.22044605e-16,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  2.22044605e-16,  3.50000000e+00,
         2.22044605e-16,  1.00000000e+00, -1.11022302e-16],
       [ 2.22044605e-16,  1.00000000e+00,  2.22044605e-16,
         3.50000000e+00,  2.22044605e-16,  1.00000000e+00],
       [ 1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         2.22044605e-16,  3.50000000e+00, -4.44089210e-16],
       [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-16,
         1.00000000e+00, -4.44089210e-16,  6.00000000e+00]])

In [6]:
np.linalg.inv(A.T @ A)

array([[ 1.80000000e-01,  5.50670620e-18, -4.00000000e-02,
        -6.92779167e-18, -4.00000000e-02, -3.46389584e-18],
       [ 5.50670620e-18,  3.20000000e-01, -1.91846539e-17,
        -8.00000000e-02,  3.90798505e-18, -4.00000000e-02],
       [-4.00000000e-02, -1.91846539e-17,  3.20000000e-01,
        -8.52651283e-18, -8.00000000e-02,  4.61852778e-18],
       [-6.92779167e-18, -8.00000000e-02, -8.52651283e-18,
         3.20000000e-01, -2.09610107e-17, -4.00000000e-02],
       [-4.00000000e-02,  3.90798505e-18, -8.00000000e-02,
        -2.09610107e-17,  3.20000000e-01,  2.50466314e-17],
       [-3.46389584e-18, -4.00000000e-02,  4.61852778e-18,
        -4.00000000e-02,  2.50466314e-17,  1.80000000e-01]])

In [7]:
np.linalg.inv(A.T)

array([[ 0.1      ,  0.2      ,  0.2      ,  0.2      ,  0.2      ,
         0.1      ],
       [ 0.2      ,  0.3236068,  0.1236068, -0.1236068, -0.3236068,
        -0.2      ],
       [ 0.2      ,  0.1236068, -0.3236068, -0.3236068,  0.1236068,
         0.2      ],
       [ 0.2      , -0.1236068, -0.3236068,  0.3236068,  0.1236068,
        -0.2      ],
       [ 0.2      , -0.3236068,  0.1236068,  0.1236068, -0.3236068,
         0.2      ],
       [ 0.1      , -0.2      ,  0.2      , -0.2      ,  0.2      ,
        -0.1      ]])

In [8]:
import sympy as sp

# 定义符号变量
r = sp.symbols('r')

# r = 2
# 定义矩阵
A = sp.Matrix([[r + 1, 0, 1],
                [0, (r + 1) / 2, 0],
                [1, 0, r + 1]])

# 计算逆矩阵
A_inv = A.inv()

# 显示逆矩阵
A_inv.simplify()
A_inv


Matrix([
[(r + 1)/(r*(r + 2)),         0,      -1/(r*(r + 2))],
[                  0, 2/(r + 1),                   0],
[     -1/(r*(r + 2)),         0, (r + 1)/(r*(r + 2))]])

In [9]:
import sympy as sp

# 定义符号变量
r = sp.symbols('r')

# r=2
# 定义矩阵
A = sp.Matrix([[r + 1, 0, 1, 0],
                [0, (r + 1) / 2, 0, 1],
                [1, 0, (r + 1) / 2, 0],
                [0, 1, 0, r + 1]])
A


Matrix([
[r + 1,         0,         1,     0],
[    0, r/2 + 1/2,         0,     1],
[    1,         0, r/2 + 1/2,     0],
[    0,         1,         0, r + 1]])

In [10]:

# 计算逆矩阵
A_inv = A.inv()

# 显示逆矩阵
A_inv.simplify()
A_inv


Matrix([
[(r + 1)/(r**2 + 2*r - 1),                          0,        -2/(r**2 + 2*r - 1),                        0],
[                       0, 2*(r + 1)/(r**2 + 2*r - 1),                          0,      -2/(r**2 + 2*r - 1)],
[     -2/(r**2 + 2*r - 1),                          0, 2*(r + 1)/(r**2 + 2*r - 1),                        0],
[                       0,        -2/(r**2 + 2*r - 1),                          0, (r + 1)/(r**2 + 2*r - 1)]])

要将上述内容扩展到任意阶导数，我们可以按照类似的推导步骤进行。以下是扩展到第 $n$ 阶导数的证明。

### Step 1: 定义函数
令 $f: \mathbb{R} \to \mathbb{R}$ 为一个 $n$ 次可导函数。定义函数 $g: \mathbb{R} \to \mathbb{R}$ 为 $f$ 在 $x_0$ 处的平移：
$$
    g(x) := f(x + x_0)
$$
其中 $x_0$ 是 $\mathbb{R}$ 中的一个固定点。

### Step 2: 计算 $g(x)$ 的第 $n$ 阶导数
要计算 $g(x)$ 的第 $n$ 阶导数，我们需要使用链式法则的高阶导数版本。第 $n$ 阶导数 $g^{(n)}(x)$ 是通过对 $g(x)$ 逐次求导数得到的。

我们先来计算 $g(x)$ 的第 $1$ 阶导数：
$$
    g'(x) = \frac{d}{dx} f(x + x_0) = f'(x + x_0)
$$
接下来，我们计算第 $2$ 阶导数：
$$
    g''(x) = \frac{d}{dx} g'(x) = \frac{d}{dx} f'(x + x_0) = f''(x + x_0)
$$
依此类推，第 $n$ 阶导数为：
$$
    g^{(n)}(x) = \frac{d^{n}}{dx^n} g(x) = \frac{d^{n}}{dx^n} f(x + x_0)
$$
使用链式法则得：
$$
    g^{(n)}(x) = f^{(n)}(x + x_0)
$$
### Step 3: 在 $x = 0$ 处进行评估
最后，我们在 $x = 0$ 处对 $g^{(n)}(x)$ 进行评估：
$$
    g^{(n)}(0) = f^{(n)}(0 + x_0) = f^{(n)}(x_0)
$$
### 结论
因此，我们已经证明了对于任意正整数 $n$，有
$$
    g^{(n)}(0) = f^{(n)}(x_0)
$$
这意味着 $g(x)$ 的第 $n$ 阶导数在 $x = 0$ 处等于 $f(x)$ 的第 $n$ 阶导数在 $x_0$ 处的值。


In [11]:
import sympy as sp
import numpy as np

# 定义符号变量
x = sp.symbols('x')

# 定义函数 f(x)
# 你可以在下面选择不同的函数类型，或者添加新的函数类型
functions = [
    x**3 + 2*x**2 + x + 1,              # 多项式
    sp.exp(x),                           # 指数函数
    sp.log(x + 2),                       # 对数函数（x + 2 避免 log(0)）
    sp.sin(x),                           # 正弦函数
    sp.cos(x),                           # 余弦函数
    sp.tan(x),                           # 正切函数
    x**2 * sp.sin(x),                    # 多项式与三角函数的组合
    sp.exp(x) * sp.cos(x)                # 指数与三角函数的组合
]

# 随机选择一种函数
f = np.random.choice(functions)

# 打印所选择的函数类型
print(f"Selected function: {f}")

# 定义导数阶数 n
n = np.random.randint(1, 10)  # 设定 n 的范围，例如从 1 到 4 阶导数

# 计算 f^(n)(x)
f_nth_derivative = sp.diff(f, x, n)

# 定义移位函数 g(x) = f(x + x0)
x0 = np.random.randint(1, 10)  # 设定 x0 的值
g = f.subs(x, x + x0)

# 计算 g^(n)(0)
g_nth_derivative_at_0 = sp.diff(g, x, n).subs(x, 0)

# 计算 f^(n)(x0)
f_nth_derivative_at_x0 = f_nth_derivative.subs(x, x0)

# 判断结果是否一致
if g_nth_derivative_at_0 == f_nth_derivative_at_x0:
    print(f"Success: g^{n}(0) = f^{n}({x0}) = {g_nth_derivative_at_0}")
else:
    print(f"Mismatch: g^{n}(0) = {g_nth_derivative_at_0}, f^{n}({x0}) = {f_nth_derivative_at_x0}")


Selected function: log(x + 2)
Success: g^9(0) = f^9(3) = 8064/390625
